mysite/enquetes/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:pergunta_id>/', views.detalhes, name='detalhes'),
    path('<int:pergunta_id>/votacao/', views.votacao, name='votacao'),
    path('<int:pergunta_id>/resultado/', views.resultado, name='resultado'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('raiz.urls')),
    path('enquetes/', include ('enquetes.urls')),
    path('simulaquiz/', include ('simulaquiz.urls')),
]

mysite/raiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
]

mysite/enquetes/models.py
import datetime
from django.db import models
from django.utils import timezone

class Pergunta(models.Model):
    texto = models.CharField(max_length=150)
    data_pub = models.DateTimeField('Data de publicação')
    def __str__(self):
        return '{} ({})'.format(self.texto, self.id)
    def publicada_recentemente(self):
        agora = timezone.now()
        return self.data_pub >= agora - datetime.timedelta(hours=24)

class Alternativa(models.Model):
    texto = models.CharField(max_length=100)
    quant_votos = models.IntegerField(
        'Quantidade de votos', default=0
    )
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return '{} ({})'.format(self.texto, self.id)

mysite/enquetes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Pergunta

# Create your views here.
def index (request):
     enquetes = Pergunta.objects.order_by('-data_pub')[:10]
     contexto = {'lista_enquetes': enquetes}
     return render(request, 'enquetes/index.html', contexto)

def detalhes (request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk = pergunta_id)
    contexto = {'enquete': pergunta}
    return render(request, 'enquetes/detalhes.html', contexto)

def votacao(request, pergunta_id):
    resultado = 'VOTAÇÃO da enquete de número %s'
    return HttpResponse (resultado % pergunta_id)

def resultado(request, pergunta_id):
    resultado = 'RESULTADO da enquete de número %s'
    return HttpResponse(resultado % pergunta_id)

mysite/enquetes/templates/enquetes/detalhes.html
<html>
    <head>
        <title>App Enquetes</title>
    </head>
    <body>
        <h1>Aplicação de enquetes - DSWeb 2024.1</h1>
        <h2>Enquetes #{{enquete.id}}</h2>
        <h2>{{enquete.texto}}</h2>
        <p><i>{{enquete.data_pub}}</i></h2>
        <p>Selecione a alternativa desejada:</p>
        <ul>
            {% for alt in enquete.alternativa_set.all %}
                <li>{{ alt.texto}}</li>
            {% endfor %}
        </ul>
    </body>
</html>

mysite/enquetes/templates/enquetes/index.html
<html>
    <head>
        <title>App Enquetes</title>
    </head>
    <body>
        <h1>Aplicação de Enquetes - DSWeb 2024.1</h1>
        {% if lista_enquetes %}
        <h3>Lista das Enquetes Cadastradas:</h3>
        <ul>
            {% for p in lista_enquetes %}
            <li><a href="/enquetes/{{ p.id }}/">
                {{ p.texto }}
            </a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <h3>Nenhuma enquete cadastrada até o momento.</h3>
        {% endif %}
    </body>
</html>